### ISSUE TITLE
how do I convert a 1 bit mono image into the format that your code expects

### ISSUE THREAD

**Issue by geetee24** [SelfDestroyer/pyMOD-OLED#1]
if i have a 1 bit black and white mono jpg, how do I convert it into a PAGE MODE format that your code expects?

Thank you.

**Comment by selfbg** [comment]
Hello,

You can use PIL for opening the file. Then use draw_pixel mode.
If uploaded simple animation example:
https://github.com/SelfDestroyer/pyMOD-OLED/blob/master/example/Draw_Bitmap.py
