### ISSUE TITLE
Image is mirrored

### ISSUE THREAD

**Issue by iondulgheru** [SelfDestroyer/pyMOD-OLED#4]
Hi
I am trying to use this library on CHIP (getchip.com)
But I run Hello_World.py the image is mirrored.
How can i flip left and right?

**Comment by selfbg** [comment]
You can try to change memory addressing mode and play with start row and column.
    
    def set_memory_addressing_mode(self, mode)

**Comment by iondulgheru** [comment]
Thank you @StefanMavrodiev .
Somehow, after a few reboots, the image is now displayed correctly, without me doing anything.
I will close this, and I will come back for your help if the issue persists.

Have a nice day!
