### ISSUE TITLE
printing text is backwards

### ISSUE THREAD

**Issue by riker65** [SelfDestroyer/pyMOD-OLED#6]
Hi
running your Hello World example
is printing the text backwords-.----

what am I doing wrong?

Thx

**Comment by selfbg** [comment]
Can you be more specific. What you mean by "backwords" ?

**Comment by riker65** [comment]
I was printing TIME and got EMIT
other way around.
strange

**Comment by selfbg** [comment]
Can you share your code?

**Comment by riker65** [comment]
Hi
mainly your example

    from oled import OLED
    from oled import Font
    from oled import Graphics
    import time
    
    # Connect to the display on /dev/i2c-1
    dis = OLED(1)
    
    # Start communication
    dis.begin()
    
    # Start basic initialization
    dis.initialize()
    
    # Do additional configuration
    dis.set_memory_addressing_mode(0)
    dis.set_column_address(0, 127)
    dis.set_page_address(0, 7)
    
    # Clear display
    dis.clear()
    
    # Set font scale x2
    f = Font(5)
    
    # Print some large text
    f.print_string(0, 0, "TIME")
    
    time.sleep(3)
    
    # Change font to 5x7
    #f.scale = 1
    #f.print_string(0, 24, "MOD-OLED-128x64")
    #f.print_string(0, 32, "olimex.com")
    
    # Send video buffer to display
    dis.update()

**Comment by selfbg** [comment]
Unfortunately I cannot reproduce your issue.

What is your setup? What board are you using? Have you checked the i2c speed?

**Comment by riker65** [comment]
Hi
how di I check the i2c speed?
I have a standard setup I think.
How to check?

it is a "normal" aliexpress oled? working fine with other libraries...

Thanks T

**Comment by selfbg** [comment]
So it's not this one?
https://www.olimex.com/Products/Modules/LCD/MOD-OLED-128x64/open-source-hardware
